### ISSUE TITLE
Armor

### ISSUE THREAD

**Issue by VDHawkin** [StasTserk/foundry-burningwheel#105]
The armor (item) does not fill the armor section of the sheet automatically like for weapons.

**Comment by StasTserk** [comment]
This isn't something I can reproduce.
Keep in mind that unlike weapons, armor needs to be specified as equipped.
![image](https://user-images.githubusercontent.com/5915880/91331898-a51e0d00-e788-11ea-8a43-fdad1f7804da.png)
