### ISSUE TITLE
Unable to add additional entries to "Gear, Possessions, and Property"

### ISSUE THREAD

**Issue by PhyDoesStuff** [StasTserk/foundry-burningwheel#126]
**Description**
Post-burning, it is not possible to add additional possessions, weapons, armor, property, or other miscellany to the "Gear, Possessions, and Property" section. A review of the codebase indicates that the function is missing instead of failing to render appropriately.

**Expected behavior**
It should be possible to add an item to this section and determine its type upon creation.  Might be worthwhile to split equipment into categories like Relationships, Reputations, and Affiliations are split.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox: 80.0.1 (64-bit)
 - Version: 0.3.3

**Comment by StasTserk** [comment]
Currently, it is possible to add those kinds of items to the sheet, but the only way to add them is via dragging items from a compendium/item tab directly onto the character sheet which is the default foundry approach for adding items.

The items are - in fact - separated in the equipment section though only though colour coding of the entry.
![image](https://user-images.githubusercontent.com/5915880/92510343-ecfd5500-f1c8-11ea-86c0-8156c05a570b.png)

I don't currently plan on changing the way the equipment section displays the different item categories, but :+1: on adding a way to import/create equipment directly from the sheet.
