### ISSUE TITLE
Support for weapons with multiple attacks

### ISSUE THREAD

**Issue by PhyDoesStuff** [StasTserk/foundry-burningwheel#127]
While it's not directly stated, all melee weapons include at least two modes of attack: the primary attack mode (such as "Knife" or "Arming Sword") and "Hilt/Pommel/Butt" (in Miscellaneous Weapon Gear, "All weapons" under Handedness for some reason). Additionally, polearm weapons have "Polearm Axe Strike" and "Polearm Thrust" attacks; and the Beak attack can be added to polearm, axe, and spear weapons. The hilt/pommel/butt attack can also be upgraded to a spiked or weighted pommel.

Recommended fix for data structure of weapons:
* Weapon name
* quality
* skillId
* shade
* handedness
* Attack data [array]
  * Attack name
  * power
  * add
  * vsArmor
  * weaponSpeed
  * weaponLength
  * I/M/S calculated per attack

When creating a new weapon, it should be possible to create additional Attacks. Auto-populating the attacks can be saved for the Compendium.

Attacks under "Weapons and Armor" should read in Attacks from existing Weapons. The name displayed could be Weapon Name + " " + Attack Name.

**Comment by StasTserk** [comment]
Good suggestion.

This would represent a pretty substantial change to the weapon data model plus a few technical unknowns on my part, so it's something that might take a while to implement, but definitely something that'll be added to a future release.
