### ISSUE TITLE
Toolkits not expending properly

### ISSUE THREAD

**Issue by PhyDoesStuff** [StasTserk/foundry-burningwheel#151]
**Describe the bug**
Toolkits selected for expending in the skill test dialogue are not being marked as Expended.

**To Reproduce**
1. Create new skill that requires a toolkit (ex. "Alchemy")
2. Create a new item that is marked as "Toolkit" (ex "test toolkit")
3. Start a new Test for skill from step 1, select toolkit from step 2 in the "Expend Toolkit?" dropdown
4. Roll Test
5. Check toolkit item in item section. The "Expended" toggle should be off

**Expected behavior**
Selecting a toolkit in the "Expend Toolkit?" dropdown and rolling a test should Expend the Toolkit.

**Comment by StasTserk** [comment]
In the case of toolkits expending, it's not properly communicated right now, but they require a DoF roll and only actually expend on a 1.

The DoF is rolled in the background, but not communicated in any way. There isn't a strict bug to fix, but I will add better communication for this in the next release.
