### ISSUE TITLE
Aptitude for skills/spells does not immediately update when modified by traits

### ISSUE THREAD

**Issue by PhyDoesStuff** [StasTserk/foundry-burningwheel#177]
Adding an aptitude modifier for spells or skills does not immediately update the aptitude required for learning a spell/opening a skill. The aptitude does update after making a test for the skill/spell. Not sure if it's recalculating aptitude after the test, or if it's just not visually updating, but examining a skill that was already being learned after applying an aptitude modifier did not show a changed aptitude in the skill dialogue.

**Comment by PhyDoesStuff** [comment]
On further examination, it looks like the aptitude is being recalculated after the roll is done. This can be verified by playing around with the aptitude for spells like so:

0. Assume aptitude of 4
1. Create a new spell
2. Add a new trait with an aptitude modifier for "spells" of -1
3. Roll test for spell created in step 1

Expected: the "in practicals" modifier should be +3 Ob for the first test, then +2 Ob, then +1 Ob
Actual: "in practicals" modifier will be +4 Ob. Subsequent rolls for the spell will have an "in practicals" modifier of +2 Ob and +1 Ob

**Comment by StasTserk** [comment]
Kind of a known issue. Related to problem described in #37 . The issue, essentially is that an update in an item automatically triggers an update of the owning actor, however, it does not trigger an update for all of the items owned by the actor which would have to happen for the skill/spell/s aptitude value to recalculate.

Simplest fix would actually be to refresh the window which should trigger the aptitude calculation on every skill and spell.

Going to consider this as relatively low priority to fix on account of
1. Traits that grant aptitude being fairly rare
2. Having a simple workaround (refreshing the browser window)
3. The solution requiring pretty substantial modification to the actor/item update code to properly notify the skills and spells to recalculate.

**Comment by StasTserk** [comment]
Through absolutely no doing on my part, it appears as though this issue has resolved itself.
