### ISSUE TITLE
Reduce penalties when a wound has been treated

### ISSUE THREAD

**Issue by PhyDoesStuff** [StasTserk/foundry-burningwheel#187]
For Midi, Severe, and Traumatic wounds, once a wound is treated via a skill check, the penalty would be reduced by 1D (see Recovery in Anatomy of Injury). There currently isn't a way to automate the reduced penalty from treating a wound, and seeing one would be pretty nice.

**Comment by StasTserk** [comment]
Had a thought about a quick mockup, perhaps something like this would be the shortest path to supporting partial recovery.
![image](https://user-images.githubusercontent.com/5915880/96520519-82f6b780-122c-11eb-8cf9-f1cda76641ad.png)

It would be something up to the users to track manually, but if you're doing the recovery roll, writing down the recovery notes, might make sense to also update a number input for recovered dice.
