### ISSUE TITLE
Alternate Character Sheet

### ISSUE THREAD

**Issue by StasTserk** [StasTserk/foundry-burningwheel#188]
It would be nice to get a sheet type that's a bit closer to the foundry default to give the option of reduced scrolling.

This task is to add a tabbed version of the sheet that splits the different sections.

**Comment by Nilsiker** [comment]
Are there any resources about, on how this could be done?

I'm very interested in this and would not mind contributing!

**Comment by Nilsiker** [comment]
I very much second this!

Are you thinking there should be a tabbed version and the current version, or should the tabbed sheet replace the current one?
I have been playing around with a tabbed version replacing the current one on my fork, and would gladly tidy it up for a PR :)

![image](https://user-images.githubusercontent.com/34456840/126070249-b8dc346f-2118-4df6-8141-63571149b6ce.png)

**Comment by StasTserk** [comment]
There has been some interest in a dabbed version of the sheet for sure.

I'm all for accepting a PR for an alternate character sheet, but it shouldn't replace the current sheet. Rather, it should be registered as another option alongside the current default.

Thanks for your interest in this! Your mockup looks pretty good, and I'd love to review it (though make sure to follow the [contribution guidelines](https://github.com/StasTserk/foundry-burningwheel/blob/master/CONTRIBUTING.md)).

**Comment by StasTserk** [comment]
To be explicit, this would require a separate template file, a separate sheet class (which could probably be extended off of the regular `BWCharacterSheet` class) and an extra entry during the [sheet registration steps](https://github.com/StasTserk/foundry-burningwheel/blob/master/module/burningwheel.ts#L26-L29)

**Comment by Nilsiker** [comment]
Perfect, that is more than enough to get me  started! :)
