### ISSUE TITLE
Ability to change the image on items

### ISSUE THREAD

**Issue by Nevenall** [StasTserk/foundry-burningwheel#249]
**Is your feature request related to a problem? Please describe.**
I have a set of images I use for items that are restricted to a particular stock, currently I have to export the item, set the image, and then import the item. 

**Describe the solution you'd like**
It would be nice if I was able to change the image from the item sheet. 
It would also be nice if the image appeared in the search box for adding existing items to a character. (or there was another way to tell the difference between items with the same name from different stocks.)

Thank you!

**Comment by StasTserk** [comment]
Right now, the "official" way to segregate items by stock is to separate them into different compendiums, then limit your sources when using the character burner and adding things through the character sheet dialogs.

That said, though I'm not incredibly stoked on turning images permanently on for all items (I myself have a lot of items set up that would all need to be changed from that mystery-man.svg default) I'm amenable to adding this in.

Probably the most thorough answer would be to offer a second character sheet for item types. I'm not incredibly interested in maintaining multiple sheets, however.

The thing I'm considering here though is to add a system setting (that I'm going to keep off by default) that would enable item images/the image setting widget.
