### ISSUE TITLE
Track fate spent on Beliefs and Traits

### ISSUE THREAD

**Issue by coreyhickson** [StasTserk/foundry-burningwheel#272]
**Is your feature request related to a problem? Please describe.**
In my games, we track artha spending on beliefs and instincts (as per pg. 59 under Evolving Beliefs and Instincts) for the trait vote we do.

**Describe the solution you'd like**
I'd love to have a way to track artha that is spent onto a belief or instinct. To me, this would include:
* Circles which would say how much artha was spent on a belief or instinct
* A way during a roll to check off if the artha being spent is going towards a belief or instinct (to automate the increments)
* A way to add and rename beliefs so we can carry them over to the trait vote

**Describe alternatives you've considered**
None considered

**Additional context**

Roll20 example which lets you increase artha spend on beliefs and instincts:
![image](https://user-images.githubusercontent.com/19170294/100947221-d1090700-34ca-11eb-87d3-91b8b42079e0.png)

Roll20 example which lets you add more than 4 Beliefs:
![image](https://user-images.githubusercontent.com/19170294/100947483-58ef1100-34cb-11eb-9a17-9867175edabc.png)

**Comment by StasTserk** [comment]
:+1: On adding support for beliefs.

I'll have to think a bit about shifting the way beliefs and instincts work from "here are the 3-4 beliefs you are allowed to define at one go" to "beliefs are discrete data objects that you slot in and out with their own ongoing tracking" and the kind of interface adjustments that would require.

**Comment by StasTserk** [comment]
Currently there *is* a way to add new beliefs to a character sheet though it is not the most obvious to people without a familiarity with foundry itself.
First by creating a belief item via the Items tab...
![create-new](https://user-images.githubusercontent.com/5915880/100949467-96ea3600-34c7-11eb-8954-89a69d199e9c.png)

Then by dragging it onto the character sheet...
![extra-belief](https://user-images.githubusercontent.com/5915880/100949830-5b03a080-34c8-11eb-9fee-41d77a468d80.gif)

**Comment by coreyhickson** [comment]
Oh wow I didn't even realize that's an option. That'd work great for our group, thanks!

**Comment by StasTserk** [comment]
A checklist of my self here:
 - [x] Add template.json entries for tracking fate.
 - [x] Add actual sheets for beliefs and instincts.
 - [x] Add ability to open beliefs and instinct sheets directly from the character sheet.
 - [x] Add ability to delete beliefs and instincts directly from the sheet.
 - [ ] Add drag and drop functionality to move beliefs around to and from the sheet.
 - [ ] Add an easier way to add beliefs directly from the sheet rather than creating new ones.
