### ISSUE TITLE
Estimate and Build out Localization Issues

### ISSUE THREAD

**Issue by StasTserk** [StasTserk/foundry-burningwheel#307]
Though there have been no explicit requests for it, now that the sheet is entering stability, it is perhaps time to look at localization for the system.

This issue is an "Epic" for now indicating that the estimation and issue breakup for the localization effort still needs to be done.

**Comment by PauloDeTiege** [comment]
Do you have an estimation of the word count of the project? I'd potentially be willing to work on a translation to Dutch.

**Comment by StasTserk** [comment]
@PauloDeTiege Unfortunately no. This issue is meant to cover the effort of estimating and parceling out the localization effort into discrete tasks, covering sheet sections, extended test dialogs, etc.

Are you interested in implementing localization for the system as a whole or more interested in creating a Dutch translation once there's some localization infrastructure in place?

**Comment by PauloDeTiege** [comment]
I'd be fine helping out with localization, but I have no programming experience so I don't know if I can offer what you need regarding that. I'd essentially be starting from zero here.

**Comment by StasTserk** [comment]
No worries, the main thing is that I don't have a lot of bandwidth these days for working on the system aside from bugfixes and Foundry VTT compatibility upgrades as per [the readme](https://github.com/StasTserk/foundry-burningwheel#state-of-development). I mostly rely on PRs for new features, but when I have a chance to work on some more features I can look at prioritizing setting up the groundwork for localization.

**Comment by agolp** [comment]
Hey, can I help with this? I'd be interesting in helping with implementing localization but don't have experience doing this in Foundry (I know the concepts and have written multilangual web apps though).

What would be a good starting point?

**Comment by StasTserk** [comment]
@agolp Hey, thanks for the interest!

The process of adding localization is pretty straightforward, but somewhat time consuming.

One part involves replacing every bit of visible text in the system with localization... placeholders.
The majority of this work involves editing handlebars templates (like `templates/sections/header.hbs`) and replacing text like

```hbs
<h2 class="section-header"><label>Character Index</label>
```
with something like
```hbs
<h2 class="section-header"><label>{{localize "character.header.character_index"}}</label>
```

A second part of that involves creating a corresponding language file, (like `/languages/en.json`) with contents including
```json
{
  "character": {
    "header": {
      "character_index": "Character Index"
    }
  }
}
```

With that done across the entire sheet, adding another language to the sheet would be just a matter of creating another language json file, and replacing the english version of each entry with some other language equivalent.

**Comment by StasTserk** [comment]
As for the best place to get started, the thing to do is to get a good inventory of the text that needs to be replaced in every part of the sheet, so we can break out the task into multiple issues that can be done independently.

Essentially, for the sake of making code review easier, and making the task a lot more modular and easier to keep track of, best place to start would be to try and compile a list of every bit of text that needs to be translated. I can use that list to create some issues on github to track the progress in the localization project board.

**Comment by StasTserk** [comment]
Actually, thinking about it some, probably I'm best suited to do that work. I have a bit of time so I think I'll spend this evening setting up some bare bones localization issues and start the groundwork for it in the system.

**Comment by StasTserk** [comment]
Estimation for the issues is all done, should be visible up on the [Localization project board](https://github.com/StasTserk/foundry-burningwheel/projects/2).
