### ISSUE TITLE
Adding Items to Compendiums

### ISSUE THREAD

**Issue by thecodex101** [StasTserk/foundry-burningwheel#343]
When adding Items to Compendiums created pre 8,x,x and after upgrading it seems I can no longer add items. 

I was previously just using drag and drop to add the items. Please note a compendium created in 8.6.0 Foundry allows drag and drop functionality just fine. 

currently running Foundry VTT 8.6.0 and Burning Wheel Version 1.1.1 

Just wondering if there was something new I had to do. Alternatively is there a good way you know to transfer all the data to a new working compendium (I have spent quiet a while recreating the Traits, skills, wises, lifepaths and gear for my group, but luckly we have not quiet started playing). 

Cheers in advance and keep up the great work.

**Comment by thecodex101** [comment]
Apologies not the bug I reported it is adding Items, but no longer sorting them alphabetically like it was all my entries were disappearing to the end of a very long list. Is there a way to fix this?

**Comment by StasTserk** [comment]
Hey, thanks for reaching out. The way compendiums behave is something defined in the core of foundry, so it would be tricky to do much to change how they act.

I have noticed this new behaviour where new items in a compendium don't automatically sort alphabetically but I found just giving the window a quick refresh fixes things.

Hope that resolves your problem.

**Comment by StasTserk** [comment]
Closing this issue since there doesn't seem like there is much for me to do here.
