### ISSUE TITLE
Preexisting embedded items not in database

### ISSUE THREAD

**Issue by jillpls** [StasTserk/foundry-burningwheel#349]
**Describe the bug**
Embedded items (belifes, instincts, etc.) that are created with an actor (character, npc) seem to not be stored in the databse, cannot be updated (error) and are missing after a reload.

**To Reproduce**
Steps to reproduce the behavior (update error)
1. Create an Actor
2. Edit a belief/instict
3. Click outside the field
4. See error: `The key f0sa7x4p4q6t9zgx does not exist in the EmbeddedCollection Collection` and the field is blank

Steps to reproduce the behavior (missing fields)
1. Create an Actor
2. Close World
3. Launch World
4. Actor sheets now have no Belief/Instinct items.

**Desktop:**
 - OS: Win 10
 - Browser Firefox
 - Version 89.0.2

**Additional context**
For Character Sheets this is not a big deal, as you can create all beliefs by hand (though still annoying), but npc sheets seem to not have an option to edit in beliefs and their embedded items are also dropped.
Foundry Version: 0.8.8 (dockerized)

**Foundry server logs error:**
```Error: The key f0sa7x4p4q6t9zgx does not exist in the EmbeddedCollection Collection
    at Map.get (file:///home/foundry/resources/app/common/utils/collection.mjs:106:13)
    at ServerDatabaseBackend._updateEmbeddedDocuments (file:///home/foundry/resources/app/dist/database/backend/server-backend.mjs:1:3394)
    at ServerDatabaseBackend.update (file:///home/foundry/resources/app/common/abstract/backend.mjs:153:31)
    at async Socket.handleEvent (file:///home/foundry/resources/app/dist/server/sockets.mjs:1:568)```

**Comment by StasTserk** [comment]
Confirmed the issue (not sure how it got past testing)

I'll push a hotfix out asap
