### ISSUE TITLE
Confirming values with ENTER reverts the tabbed sheet to the BITs tab

### ISSUE THREAD

**Issue by Nilsiker** [StasTserk/foundry-burningwheel#356]
**Describe the bug**
When confirming value fields with ENTER, the character sheet reverts to the BITs tab, instead of staying at the currently chosen tab.

**To Reproduce**
1. Create a new or choose an existing character.
2. Switch to a tabbed character sheet by clicking the ⚙Sheet button.
3. Switch to Skills & Spells and edit any skill exponent.
4. Confirm the value with ENTER

**Comment by Nilsiker** [comment]
My guess is that the sheet refreshes when submitting the new values, and the currently chosen tab isn't a saved state. I'm not too familiar with the Foundry API just yet, but I reckon it should be a fairly simple fix.

Any immediate ideas on where to look/tinker? 😃

**Comment by StasTserk** [comment]
Having originally set out to make a sheet that is explicitly not tabbed, I'm also somewhat unfamiliar with how tabs work with rendering.

I do know that foundry does try to preserve some things (like which input was last focused) between renders which might also extend out to the active tab as well. However, that behaviour usually relies on an input's name which isn't (and shouldn't be) present for inputs that are bound to embedded documents like spells, etc.

I would poke around the whole class inheritance chain looking at `render` and `_render` to see if there's any mention of active tabs.

WIth focused input the code in foundry is something like
```
find currently focused input
new html = super.render( ... )
set matching input as focused
```
Maybe there's something around there for tabs as well?

**Comment by StasTserk** [comment]
The other thing you might want to check is if it's something that only happens on pressing enter, there might be some particular foundry keybinds that are being triggered?

If you don't find anything, I might have a look tonight when I'm done with work.

**Comment by Nilsiker** [comment]
No idea for a solution yet, but I did found something - and oh boy is it something.

![image](https://user-images.githubusercontent.com/34456840/127535279-8152a66a-f4ee-405f-8780-b0813393ce50.png)

So, submitting with Enter executes the _clickNav method in foundry.js. It passes a PointerEvent where the (clientX,clientY) is (0,0). The tab is then chosen by finding the 'physically' closest tab - which is the leftmost one.

**Comment by StasTserk** [comment]
This is quite a bizarre issue. It seems to happen with just about any input at all, even things that are part of the core sheet (Name, Stock, Age, the Artha inputs etc.) so it doesn't have to do with even the fact that spells and skills are embedded items.

However, a system like 5e doesn't have this issue, so there's something specific to Burning Wheel going on, it seems.

And of course, the stack trace inside of `_onClickNav` is completely empty, so it doesn't look like there's anything actively triggering a click event.

**Comment by StasTserk** [comment]
Ok, yeah, it's become obvious what's happening. 🤦 

Hitting enter is trying to trigger a form submission. All buttons that don't specify a type specify `type="submit"` by default, so, hitting enter on an input contained in a form causes the browser to find the first `submit` type button element it finds and press it.

Not incredibly obvious what the correct fix is (other than people just not hitting enter, which might be a valid answer). Even changing the tags in the nav to `a` from `button` (which might make sense anyway, semantically)  or specifying `type="button"` doesn't preclude the fact that other buttons will just get hit first instead. Changing all buttons to specify a type seems like quite a bit, also but might be correct?

**Comment by StasTserk** [comment]
Regardless, If this is still open come the weekend I'll get about fixing it, but I also won't be averse to a PR just kind of mysteriously showing up 😉 

Either way, good find.

**Comment by Nilsiker** [comment]
Provided I'm not exhausted after work tonight, I'll check it out! :)

**Comment by Nilsiker** [comment]
Provided I'm not exhausted after work tonight, I'll check it out! :)
