### ISSUE TITLE
Challenging advancement checks for skill rolls are not automatically added

### ISSUE THREAD

**Issue by jpwpk** [StasTserk/foundry-burningwheel#364]
**Describe the bug**
When rolling a skill roll of Challenging difficulty, the chat dialogue will state it is Challenging, but the advancement 'dot' for a Challenging roll does not appear under the relevant skill. 

**To Reproduce**
1. Go to any opened Skill on an Actor / Character Sheet
2. Click on the dice icon to roll dice
3. Either manually add an Obstacle which would provide a Challenging difficulty, or have the GM provide an appropriate Ob (either way reproduces the issue)
4. Click button to roll dice. 
5. The Chat window displays the roll results, and correctly states that it is "Challenging' difficulty, but the advancement check for a Challenging roll does not appear under the rolled skill.

**Expected behavior**
I expect the Challenging advancement check to be added to the rolled skill. It seems to work for other difficulties on skill rolls and stat rolls i.e
Skill rolls vs Routine or Difficult do automatically add advancement 'dots' to the skill. 
Stats rolls vs Difficult or **Challenging** also automatically add the 'dots' to the relevant skill. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Browser : Firefox
 - Foundry v 0.8.9 
 - BW module v1.1.6

**Comment by StasTserk** [comment]
🤦 

Tracked down the issue. Super easy fix.
