### ISSUE TITLE
Update system to Foundry V10

### ISSUE THREAD

**Issue by Saraiguma** [StasTserk/foundry-burningwheel#388]
As per the title, once I updated to v10 I could no longer open character sheets or see character data for NPCs or PCs

**Comment by BBBNBBB** [comment]
I had the same issue. The system has not been updated for the new version yet.
Just go to the Foundry website and download the version you were on before. Remember to back up everything in Foundry user data before downgrading.

**Comment by StasTserk** [comment]
Yep, this is a "known issue" Foundry v10 released this past week and I haven't had the time to grapple with what is a pretty substantial change to the way foundry behaves at a low level.

Hopefully by the end of either this long weekend or the next weekend I'll have something at a reasonable state ready to release in a v10 compatible state.

Since I haven't actually created an "Update to v10" issue for myself yet, I'm going to commandeer this issue for that purpose.

**Comment by miniwolf** [comment]
I made this for myself, based on your repo: https://github.com/miniwolf/foundry-burning-wheel-js
I got so far that I have the character sheet opened, and rolled a skill check. I have no warnings or errors in my console at this point.

I just modified the javascript files directly. But I am missing testing on this. I will be testing it with my players in a couple of weeks. (Hopefully)
But if someone would like to try this out and report the very likely bugs in this, I will be happy to update this javascript implementation.
For those interested, the changes are mostly changing `.data` -> `.system` in various places.

**Comment by StasTserk** [comment]
@miniwolf Good to hear you got things working relatively easily.

I'll definitely be doing comprehensive testing of the system as part of my update work, but let me know if you find anything acting strangely with your updates. I'll have to implement things with typescript, of course, but it's always good to have more input about any issues I might miss myself.

**Comment by StasTserk** [comment]
Adding the following progress list to track testing
 - [x] Basics: Compiling, game launches, sheets open

### Character sheets:
 - [ ] General lack of errors and warnings
 - [x] Sheets open, data displayed as a minimum
   - [ ] PC Sheet features work
     - [ ] Armor locations
     - [ ] training skills
     - [ ] learning section
     - [ ] Weapon skill picker
     - [ ] Traits display normally
     - [ ] Settings page works
     - [ ] PTGS updated properly
 - [ ] Rolling works
   - [ ] Artha tracked
   - [ ] Forks added properly
   - [ ] Wounds apply
   - [ ] Traits apply
 - [ ] Rolling works fine
   - [ ] Artha rerolls work
   - [ ] General lack of warnings
 - [ ] Extended test dialogs work
   - [ ] Synchronized across networks
   - [ ] Actions correctly available, updated
   - [ ] Persisted properly
 - [ ] Character burner
   - [ ] Can create character stats
   - [ ] Calculation works
   - [ ] Importing compendium items works
   - [ ] Drag and drop skills/etc.
   - [ ] Drag and drop lifepaths.

**Comment by thecodex101** [comment]
Just going to ask is there a Beta Candidate that I can help do bug testing against for you ?

**Comment by StasTserk** [comment]
@thecodex101 bad news: not really planning a beta, good news: latest version that is meant to be compatible with v10 is out on official channels now.

**Don't forget to back up your world before updating**

More than likely a decent number of bugs still exist for intrepid testers to discover.

**Comment by thecodex101** [comment]
That’s great many thanks....
