### ISSUE TITLE
Cannot open existing characters or create new characters in v1.3.1 on v9 build 269

### ISSUE THREAD

**Issue by A554551N** [StasTserk/foundry-burningwheel#394]
**Describe the bug**
Burning Wheel system updated to 1.3.1 recently, now cannot open characters or create new characters in any existing Burning Wheel World.

Of note, on load a message banner reading "Beginning 0.2.1 data migration" is displayed on every load.  I haven't seen any confirmation that migration has completed despite leaving the system running for 10+ minutes.

**To Reproduce**
Attempt to open existing character
Attempt to create new character

**Expected behavior**
The character sheet to open

**Screenshots**
When the "Beginning 0.2.1 Data Migration" banner is displayed, the following error appears in the console:
![image](https://user-images.githubusercontent.com/22299332/193170825-0aff5388-5fe5-4861-b3eb-77e051b5bbe6.png)

When attempting to open an existing actor, the following error appears in console:
![image](https://user-images.githubusercontent.com/22299332/193170896-e5c5bf32-ce31-4b6a-8b35-c2f714e76e4b.png)

When attempting to create a new actor, the following error appears in console:
![image](https://user-images.githubusercontent.com/22299332/193170948-2bcf7cbe-1350-47de-a86d-c8ac1de0a8f8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Foundry Native Application
 - Version v9 build 269

**Additional context**

**Comment by StasTserk** [comment]
1.3.0 and later version explicitly put the minimum version of the system as 10. It is not compatible with version 9.
