### ISSUE TITLE
Spell IMS isn't multipling correctly, and Missile length is missing

### ISSUE THREAD

**Issue by Marcloure** [StasTserk/foundry-burningwheel#397]
**Describe the bug**
If you create a spell and mark it as "Is a Weapon", the IMS it displays is the Will+modifiers for all three degrees. It should be 0.5 * Will / Will / 1.5 * Will (rounded according to the rules):

![image](https://user-images.githubusercontent.com/29084710/208410237-2dfa19e7-dc06-4d2e-8bfd-c5552605f064.png)

Also, it's missing an option for Missile in Weapon Length after Longest.

**Comment by StasTserk** [comment]
Missed the notification for this bug report, sorry. I'll look into this soon.

**Comment by Marcloure** [comment]
Hello. The IMS is fixed, but spells are still missing the Missile weapon length after Longest!
