### ISSUE TITLE
Version 10 Stable - Patch 6 compatibility 

### ISSUE THREAD

**Issue by AJtheRonin** [StasTserk/foundry-burningwheel#398]
**Describe the bug**
The system is not compatible with the latest version available. 

![321206786_538454394974792_7669312722143996690_n](https://user-images.githubusercontent.com/64420850/210405226-1c1bc4af-2b95-4375-a971-f5526126333c.png)

**Comment by StasTserk** [comment]
The system should be compatible with the latest foundry build as there aren't any breaking changes I'm aware of.
I can update the compatibility values on the system manifest when I have some time later.

The message that the system isn't compatible with build 291 is something on Forge's end. Perhaps there's something you can do to bypass it? I don't use forge myself.
