### ISSUE TITLE
Support for Foundry V12.

### ISSUE THREAD

**Issue by MTVExtreme** [StasTserk/foundry-burningwheel#511]
Foundry version 12 changed quite a few things broke. If I were more skilled with developing systems on Foundry I'd take a look myself lol. 

Currently not even the character sheets will load. 

Going to stick on V11 until this is resolved, but figured I would open a ticket since no one else has yet.

**Comment by StasTserk** [comment]
This is definitely on the agenda, just haven't had time to address it just yet. Thanks for bringing this to my attention.
