### ISSUE TITLE
Character burning not updating stats

### ISSUE THREAD

**Issue by Conalt8** [StasTserk/foundry-burningwheel#520]
**Describe the bug**
Stats and Attributes dont update on the main page when entered during character creation using the character burner.

**To Reproduce**
Create a new character, use the character burner.
Enter Stats and Attributes values and complete the burn.

**Additional context**
Bug is happening both through the foundry app and browser.
Custom Attributes added using the character burner also dont carry over.
Skills are carried over correctly though.
Thanks for your time!

**Comment by StasTserk** [comment]
Just got back from a work trip. I'll try and have a look at this over the weekend.

**Comment by Aliharu** [comment]
Just ran into this as well.

It seems to effecting everything set in baseCharacterData.

My guess is the actor update in _finishBurning with baseCharacterData isn't actually updating the data.
