### ISSUE TITLE
Poor Quality weapon displaying as Superior Weapon in roll dialog

### ISSUE THREAD

**Issue by Marcloure** [StasTserk/foundry-burningwheel#522]
**Describe the bug**

The image bellow shows the roll dialog for a Poor Quality weapon. The text reads as a Superior Quality weapon, but it behaves correctly as a Poor Quality weapon, adding +1 Ob penalty to the roll. Also, this automation only happens for PC rolls, not NPC rolls.

I investigated the localization, and the `poorQuality` key is correctly localized, so the issue isn't there.

**Expected behavior**
It should read Poor Quality.

**Screenshots**
![image](https://github.com/user-attachments/assets/53457468-0896-4cd1-9120-4952b2f0d87f)

**Comment by StasTserk** [comment]
Looks like it's setting the wrong text for the modifier [here](https://github.com/StasTserk/foundry-burningwheel/blob/master/module/rolls/rollWeapon.ts#L80). Some sort of copy paste error from the localization effort.

I can see about getting a fix out this weekend of nobody beats me to it.

**Comment by Marcloure** [comment]
Opened a PR for this issue: https://github.com/StasTserk/foundry-burningwheel/pull/523
