### ISSUE TITLE
Issue when Multiple Sheets are Opened

### ISSUE THREAD

**Issue by pedroleone** [StasTserk/foundry-burningwheel#63]
**Describe the bug**
When multiple character sheets are open at the same time, some functions do not work as expected.

**To Reproduce**
1. Open first action
2. Open second actor
2. Click on any Coordinate on the Injury and Recovery on the second actor
3. No wound is marked on the second actor, but the wound is marked on the first

The same behavior happens when opening the skills list.

**Expected behavior**
An action in one actor should only affect the same actor.

**Screenshots**
![image](https://user-images.githubusercontent.com/4059379/88831271-7fabdc80-d1a5-11ea-9ddf-a9ca92030a06.png)

**Comment by pedroleone** [comment]
@StasTserk also I have a lot of questions about the character sheet, as I can't seem to find a button to add new skills, gear, weapons, armor. Is there a preferred place to post these questions?

**Comment by StasTserk** [comment]
@pedroleone Thanks for the bug report. I have a good idea as to the cause and I'll add it to the next release.

As for sheet questions, right now the best place to ask those is on the foundry discord or by DMing me directly on discord at Stas#3016

**Comment by StasTserk** [comment]
@pedroleone Issue should be resolved now. It's slated to come with the next release sometime this week.
